version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./share/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  alloy:
    image: grafana/alloy:latest
    ports:
      # - "12345:12345"
      - "4317:4317"  
      - "4318:4318" 
    volumes:
      - ./share/alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - "run"
      - "/etc/alloy/config.alloy"

  tempo:
    image: grafana/tempo:latest
    ports:
      - "4320:4317"  # otlp grpc
      - "4321:4318"  # otlp http
    volumes:
      - ./share/tempo/tempo.yml:/etc/tempo.yml
    command:
      - '--config.file=/etc/tempo.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./share/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=tempoServiceGraph
#  shoehub:
#    image: aussiearef/shoehub
#    ports:
#      - "8001:8080"
#
#  orderservice:
#    image: aussiearef/orderservice
#
#  paymentservice:
#    image: aussiearef/paymentservice
#
#  stimulator:
#    image: aussiearef/stimulator
#    depends_on:
#      - orderservice
#      - paymentservice

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      - OTLP_ENDPOINT=your-otlp-endpoint:4317

  payment_service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
#    environment:
#      - OTLP_ENDPOINT=your-otlp-endpoint:4317
